apiVersion: v1
kind: PersistentVolume
metadata:
  name: prateek-pv
  namespace: demo
  labels:
    type: prateek-pv
spec:
  claimRef:
    name: prateek-pvc
    namespace: demo
  capacity:
    storage: 11Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/lib/redis
